### ISSUE TITLE
What is the host and websocket uri to be used

### ISSUE THREAD

**Issue by pannet1** [ProfitmartAPI/ProfitmartAPI-Py#1]
@Nikhesh 
What is the host and websocket uri to be used while inititating NorenAPI. the broker is Profitmart

**Comment by ProfitmartAPI** [comment]
Hi, Please find below attached Url for API and we socket Url.

https://profitmax.profitmart.in/NorenWClientTP/
wss://profitmax.profitmart.in/NorenWSTP/

**Comment by maheshtrade88** [comment]
What is the current host and websocket uri to be used while inititating NorenAPI. the broker is Profitmart. The above is not working

**Comment by Nikhesh** [comment]
Hi team ,



Its for LIVE or UAT ?



Thanks and regards,

Nikhesh P






---- On Thu, 08 Jun 2023 17:51:44 +0530 pannet1 ***@***.***> wrote ---





https://github.com/Nikhesh
 What is the host and websocket uri to be used while inititating NorenAPI. the broker is Profitmart
